[package]
name = "imagecodes"
version = "0.3.1-alpha.0"
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"
publish = false

[dependencies]
qrcode = "0.12.0"
image = "0.23.3"
mime = "0.3.13"

log = "0.4.6"
env_logger = "0.7.1"
proptest = "0.9.4"

# Webserver/Async stuff
tide = "0.7.0"
http-types = "1.0.1"

[dependencies.async-std]
version = "1.5.0"
features = ["attributes"]

[dev-dependencies]
pretty_assertions = "0.6.1"
http-service-mock = "0.5.0"

[profile.dev]
opt-level = 2
